### ISSUE TITLE
[ Report mock_hardware ] - Provide information whether we are running on mock hardware or not

### ISSUE THREAD

**Issue by firesurfer** [UniversalRobots/Universal_Robots_ROS2_Driver#1021]
### Feature summary

In our system we have several components that are either mocked or that control real hardware. For testing purposes it is really useful to mix both modes. 

I couldn't figure out a way yet to determine whether a UR hardware interface is mocked or running or real hardware. 

I think it would be nice of the status controller could provide that information. What do you think?

# Implementation

I have no idea what the best way to implement this is. For my own ros2 control hardware interfaces I solved it by not using the generic mock components but by providing my own mocked interface in the communication layer below. So the hardware interface is always loaded  and I can provide a StateInterface with the needed information.

**Comment by fmauch** [comment]
How exactly would you plan to use it?

`ros2 control list_hardware_components` already provides that information:

``` console
$ ros2 control list_hardware_components
Hardware Component 1
        name: ur5e
        type: system
        plugin name: ur_robot_driver/URPositionHardwareInterface
        state: id=3 label=active
```

``` console
$ ros2 control list_hardware_components
[INFO] [1718785882.878497337] [_ros2cli_2761454]: waiting for service /controller_manager/list_hardware_components to become available...
Hardware Component 1
        name: ur5e
        type: system
        plugin name: mock_components/GenericSystem
        state: id=3 label=active
```

Obviously, wrapping this in a service call or even broadcasting this via a topic might be an appropriate thing to do, but that would have to be handled inside ros2_control. Would this cover your use-case?
