### ISSUE TITLE
is the UR20 supported ?

### ISSUE THREAD

**Issue by muttistefano** [UniversalRobots/Universal_Robots_ROS2_Driver#1061]
### Feature summary

Hi All,
I just wanted to ask if the UR20 is supported by the driver.
Thanks

**Comment by fmauch** [comment]
Yes.

What would make you think the UR20 is not supported? Then we can maybe improve on that.

**Comment by muttistefano** [comment]
hi @fmauch and thanks for the answer.
I was mislead by the phrase "from 3 kg payload to 16 kg payload and includes both the CB3 and the E-series.", because the ur20 is not listed as CB3 on their site, and also not as e-series.
Nice to know it works btw.
Thanks

**Comment by fmauch** [comment]
Thanks for pointing that out. We will update the README accordingly, maybe also with another picture showing the whole family.  I'll re-open this until this is done.
