### ISSUE TITLE
License question for non code files in this repository

### ISSUE THREAD

**Issue by firesurfer** [UniversalRobots/Universal_Robots_ROS2_Driver#1095]
### Feature summary

I would like to use the image with multiple URs in the readme (https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/raw/main/ur_robot_driver/doc/installation/initial_setup_images/family_photo.png)  

Just to make sure: Is it also BSD3 ?

**Comment by fmauch** [comment]
I've taken that question back to the responsible persons as I cannot give any legal statement here.

**Comment by firesurfer** [comment]
Quick follow up: UR is willing to give licenses for certain use cases if you contact them directly.

**Comment by urrsk** [comment]
Please contact UR at pr@universal-robots.com to get a license and pictures as well.
Thanks @firesurfer asking this question
