### ISSUE TITLE
failing to execute "rosdep install" command mentioned in step-3 without  errors.

### ISSUE THREAD

**Issue by lalat-das** [UniversalRobots/Universal_Robots_ROS2_Driver#110]
Hi 
I was trying to build the UR ROS2 driver while executing the command mentioned in step -3 i.e. 
`rosdep install --ignore-src --from-paths src -y -r`

it fails with following error:

> **ERROR: the following packages/stacks could not have their rosdep keys resolved
> to system dependencies:
> joint_trajectory_controller: No definition of [realtime_tools] for OS version [bionic]
> diff_drive_controller: No definition of [realtime_tools] for OS version [bionic]
> forward_command_controller: No definition of [realtime_tools] for OS version [bionic]
> ros2_control_demo_robot: No definition of [joint_state_publisher_gui] for OS version [bionic]
> ur_description: No definition of [xacro] for OS version [bionic]
> ur_bringup: No definition of [xacro] for OS version [bionic]
> ur_controllers: No definition of [realtime_tools] for OS version [bionic]**
> Continuing to install resolvable dependencies...
> #All required rosdeps installed successfully
> 

ROS2 setting looks as below

> $ printenv | grep ROS 
> ROS_VERSION=2
> ROS_LOCALHOST_ONLY=0
> ROS_PYTHON_VERSION=3
> ROS_DISTRO=foxy

Is it that it cant be compiled for target ubutnu version 18.04. (bionic). Or Am I missing to execute/source some configurational settings ? 

Thanks
Das

**Comment by urrsk** [comment]
I do not know. The ros:foxy docker is based on ubuntu focal!
Maybe you can use this docker file to get forward: https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_robot_driver/resources/Dockerfile

**Comment by gavanderhoorn** [comment]
How did you install ROS 2 @lalat-das ? Foxy is not supported on Ubuntu Bionic, so you must have built from sources.

If you did, you cannot use `rosdep` to install ROS package dependencies any more (ie: packages like `xacro` and `realtime_tools`). You'll have to build those from source as well.

**Comment by lalat-das** [comment]
Thanks for the response. I will move my host OS to 20.04 to restrain from any further compatibility issues. Kindly close the issue.
