### ISSUE TITLE
Unable to set IO while control script isn't running

### ISSUE THREAD

**Issue by urmahp** [UniversalRobots/Universal_Robots_ROS2_Driver#111]
As setting the IO doesn't require the control script I would expect that it is possible to set IO both when the control script is running, but also when the control script isn't running. Currently it is only possible to set the IO's, when the control script is running. 

I think the above is related to the fact, that the function checkAsyncIO is only called once the control script is actually running, see [hardware_interface line](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_robot_driver/src/hardware_interface.cpp#L518).

Another thing is that I would expect the service /io_and_status_controller/set_io to return false, when the IO's aren't set on the robot. Currently the service returns true when setting the IO's even though the IO's aren't set on the robot. This happens when setting the IO's while the control script isn't running.

**Comment by MGBla** [comment]
Thanks for the input. You are right obviously. I moved the Async call outside of the check whether the program is running or not. Same applied for the speed slider.(See #112 )
