### ISSUE TITLE
Investigate the update rate of the control loop

### ISSUE THREAD

**Issue by destogl** [UniversalRobots/Universal_Robots_ROS2_Driver#123]
"Pipeline Producer overflowed..." #113 seems to detect a behavior where this driver reads data too slow from the client library. To know more we should measure the time needed for the whole control loop. A good place for this would be read or write methods of the driver. If the measured time is not approximately the same then each controller has to be checked how long `update` methods take.

The checks have to be done using:
- usual PC or Laptop
- RaspberryPI or Jetson boards using ARM processors.

**Comment by fmauch** [comment]
Closing this due to closed #113
