### ISSUE TITLE
Check why C++17 is used and if it is possible to use C++14 for the foxy release.

### ISSUE THREAD

**Issue by destogl** [UniversalRobots/Universal_Robots_ROS2_Driver#129]
The binary build seems to fail as the released version uses the `boost` branch of the library instead of the `master` branch. Therefore, it doesn't export a c++17 dependency and therefore the build fails on all c++17 functionalities from this driver.

I decided to release the foxy version also from the boost branch, as the [target platform specification}(https://www.ros.org/reps/rep-2000.html#foxy-fitzroy-may-2020-may-2023) specifies c++14 for Foxy as minimum requirement.

It might be either a good idea to add the c++17 requirement to this driver or release the library's foxy package from the `master` branch. Any opinions?

_Originally posted by @fmauch in https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/125#issuecomment-854532741_

**Comment by destogl** [comment]
After discussion, we should go with C++17 to avoid boost dependency. Consequences of this decision should be considered.

**Comment by fmauch** [comment]
Then I'll release the next foxy library version from the master branch. There will be a new release with the Cartesian interface pretty soon, anyway.

**Comment by fmauch** [comment]
I triggered a new release for Foxy from the master branch (see https://github.com/ros/rosdistro/pull/29954)

**Comment by fmauch** [comment]
@destogl this could probably get closed, right?

**Comment by fmauch** [comment]
Closing this due to seemingly irrelevance.
