### ISSUE TITLE
Ready set_io service, while inactive gpio_controller results in controller crashing

### ISSUE THREAD

**Issue by urmahp** [UniversalRobots/Universal_Robots_ROS2_Driver#148]
Once in a while it happens that the service set_io is ready, but the gpio_controller is not active yet. If you call the service set_io, while the controller is not yet active, it will result in the controller crashing.

I see it happening once in a while during the set_io_test, where the service set_io is ready, but the gpio_controller isn't active, this will result in the test failing, because the gpio_controller crashes. A workaround for the test could be to wait for the controller to be active before calling the set_io service, see [here](https://github.com/urmahp/Universal_Robots_ROS2_Driver/blob/stabilize_test/ur_robot_driver/test/integration_test.py#L153-L164). This will prevent the test from failing once in a while due to this issue.

**Comment by livanov93** [comment]
Thanks for this, the test crash was happening quite often and it was really strange and hard to detect it. We could also move service server initialization from within [on_configure](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/9acf43a670a3bca8f6637b823f518fed38dc4b65/ur_controllers/src/gpio_controller.cpp#L139)  to within [on_activate](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/9acf43a670a3bca8f6637b823f518fed38dc4b65/ur_controllers/src/gpio_controller.cpp#L223)
