### ISSUE TITLE
Build status does not update correctly

### ISSUE THREAD

**Issue by livanov93** [UniversalRobots/Universal_Robots_ROS2_Driver#174]
[Build status in the README.md](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver#build-status) does not update its flags and badges correctly.

**Comment by urrsk** [comment]
A lot of the builds are red! In addition, the badge url for the semi and source build are the same for all the three..!

I have here added the branch argument to the url for foxy. But are the CI running in that branch?

ROS2 Distro | Foxy  | Galactic | Rolling
:---------: | :---: | :------: | :-----:
**Branch** | [foxy](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/tree/foxy) | [main](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/tree/main) | [main](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/tree/main)
**Build Status** | [![Binary Build - Foxy](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-binary.yml/badge.svg?branch=foxy)](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-binary.yml?branch=foxy) <br /> [![Semi-Binary Build](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-semi-binary.yml/badge.svg?branch=foxy)](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-semi-binary.yml?branch=foxy) <br /> [![Source Build](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-source.yml/badge.svg?branch=foxy)](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-source.yml?branch=foxy) | [![Binary Build - Galactic](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-binary-galactic.yml/badge.svg)](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-binary-galactic.yml) <br /> [![Semi-Binary Build](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-semi-binary.yml/badge.svg)](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-semi-binary.yml) <br /> [![Source Build](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-source.yml/badge.svg)](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-source.yml) | [![Binary Build - Rolling](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-binary-rolling.yml/badge.svg)](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-binary-rolling.yml) <br /> [![Semi-Binary Build](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-semi-binary.yml/badge.svg)](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-semi-binary.yml) <br /> [![Source Build](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-source.yml/badge.svg)](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-source.yml)

https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/ci-build-source.yml/badge.svg?branch=foxy

**Comment by livanov93** [comment]
@urrsk Yes, the CI is also running for `foxy` branch. We need a PR to tackle this. Currently the build status on the main branch does not update correctly, the foxy branch CIs are passing at the moment.

**Comment by urrsk** [comment]
@livanov93 Okay, so maybe you can use my suggestion for show the status on the foxy branch

**Comment by livanov93** [comment]
@urrsk The link you provided is more than half of the work that needs to be done. Thank you!
