### ISSUE TITLE
Colcon build error

### ISSUE THREAD

**Issue by ravi-kumaaar** [UniversalRobots/Universal_Robots_ROS2_Driver#196]
Im currently using ROS2 foxy branch and by following the steps described i get the following error:

![Screenshot from 2021-10-06 23-56-49](https://user-images.githubusercontent.com/83002366/136289170-72bc035d-83b2-4b60-89ca-90ef94581665.png)

Unfortunately I am not good to debug these kinds of error, so i hope someone could help me?

**Comment by ravi-kumaaar** [comment]
Well, it kinda work but is probably not the final solution.

I did this in order ( starts in ws in src folder) : 
- git clone --branch=foxy https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver.git
- cd ..
- colcon build
Got some error and googled to use this
- rosdep install --ignore-src --from-paths src -y -r
- colcon build
Got some more errors with ur_msgs
- cd src
- git clone --branch=ros2 https://github.com/destogl/ur_msgs.git
- cd ..
- colcon build
- source install/setup.bash
- ros2 launch ur_description view_ur.launch.py ur_type:=ur5e

Rviz will how and everything will be ok. However, other launch files do not work properly.

@NebuDa my src/Universal_Robots_ROS2_Driver/Universal_Robots_ROS2_Driver.repos File. shows almost the same except control_msgs, but it says galactic-devel. I git clone foxy branch, do you know how to clone it properly? Tried deleting the folder and clone the right branch but didnt colcon build properly.

**Comment by livanov93** [comment]
@ravi-kumaaar If you have followed all the steps fro [Getting Started](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver#getting-started) you wouldn't need to clone packages manually.
The foxy branch .repose file states `control_msgs` should be on the foxy-devel branch. Check once more which branch are you using currently?
