### ISSUE TITLE
Support of CB2 robots

### ISSUE THREAD

**Issue by liushuya7** [UniversalRobots/Universal_Robots_ROS2_Driver#199]
Does this ROS2 driver support CB2 robots?
* [Feature list and roadmap](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/b4cb4fc67b16d40c9150098e3b8b018328090efc/ur_robot_driver/doc/features.md#L17) doesn't say yes or no.

I have a CB2 robot, and I wish I can use this package to control it.

**Comment by gavanderhoorn** [comment]
The underlying `Universal_Robots_Client_Library` uses RTDE for most things. CB2 controllers don't support RTDE.

**Comment by liushuya7** [comment]
Thanks!
