### ISSUE TITLE
scheduled binary builds are not running on expected branches?

### ISSUE THREAD

**Issue by fmauch** [UniversalRobots/Universal_Robots_ROS2_Driver#201]
I just tried to build a new workspace on ROS foxy using the binary-build method, so only with `ros2_control_demos`, `Universal_Robots_Client_Library`, `Universal_Robots_ROS2_Driver`, `ur_msgs` inside my workspace and it failed.

One outcome of this is #200 and the other one is that I noticed, while the README shows a green badge for the foxy binary build, the [workflow history](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/foxy-binary-build.yml) doesn't look that good.

I am assuming, that this is not intentional. Unfortunately, running scheduled builds on branches isn't as straight-forward as it is with push/PR triggers. See also [this post](https://stackoverflow.com/questions/58798886/github-actions-schedule-operation-on-branch) for details. However, modifying the `checkout` job directly as suggested there, would probably destroy running the workflow properly on PRs. With that, one would probably need a separate workflow file for the scheduled build...

**Comment by livanov93** [comment]
@fmauch Thank you for the heads up! CI workflow definitely needs more attention.

**Comment by fmauch** [comment]
A lot changed since this issue was originally posted. We're currently putting in a lot of effort making all steps green. Once this is done, we can re-check whether everything is linked inside the READMEs as expected.

**Comment by fmauch** [comment]
This is done by now.
