### ISSUE TITLE
tool communication question

### ISSUE THREAD

**Issue by GewoonMidas** [UniversalRobots/Universal_Robots_ROS2_Driver#202]
Hello,

I want to set up my UR5e with the Robotiq 2f-85 gripper. In the ur_robot_driver directory there is a script to activate tool communication, the documentation mentions that i have to provide a flag to activate the tool communication. If i look at the UR5e launch file it seems there is no flag for tool communication. The feature list says it is possible to use it, is it nor possible anymore to use? If it is possible to use could someone explain to me how to active the tool communication?

Thanks in advance

**Comment by gavanderhoorn** [comment]
This functionality is disconnected from anything ROS (at least it is in the ROS 1 version).

It relies on `socat` being available on the ROS pc. That just needs to be started somehow (probably as part of the launch file).
