### ISSUE TITLE
Ur5e Driver with Cpp MoveIt Interface

### ISSUE THREAD

**Issue by makeadl** [UniversalRobots/Universal_Robots_ROS2_Driver#228]
Hello,
is there an example of how to move the ur5e with cpp-moveit-interface ?

**Comment by destogl** [comment]
Hi,

Thanks for your question. If you have a robot running with MoveIt and you are not sure about MoveIt CPP interface, then can you please check MoveIt2 tutorials and if this is missing, ask on MoveIt2 repository.

You are welcome to close this issues if you have only issues with MoveIt cpp interface.
