### ISSUE TITLE
Ignition from required to optional dependency

### ISSUE THREAD

**Issue by livanov93** [UniversalRobots/Universal_Robots_ROS2_Driver#240]
We have to enable people to use bare-bone driver.
We should make Ignition as optional dependency for user that aim to do work with that simulator. Currently it is required dependency, added into main `ur_control.launch.py` file, which can't be run if ignition is not installed and the ros ignition wrapper is built in the workspace.
TODO:

- add .repos file for users that want to use ignition (see example for moveit within the driver repo)
- add additional documentation for build/install procedure for ignition users, current links are dead
- add separate launch file, don't mix it into ur_control.launch.py (include it, but don't change it)

@vatanaksoytezer please address theses changes after the work you have put into #232 
Thanks!

**Comment by fmauch** [comment]
I think, this can be close by now.
