### ISSUE TITLE
Update documentation in ROS_INTERFACE.md

### ISSUE THREAD

**Issue by livanov93** [UniversalRobots/Universal_Robots_ROS2_Driver#255]
Update documentation: [here](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_robot_driver/doc/ROS_INTERFACE.md)

**Comment by destogl** [comment]
@livanov93 please add more informations on what has to be updated.

**Comment by fmauch** [comment]
This should be closed by now...
