### ISSUE TITLE
RViz output in default launch "hides" node output

### ISSUE THREAD

**Issue by fmauch** [UniversalRobots/Universal_Robots_ROS2_Driver#259]
Just a minor comment. With the default launch file

```
ros2 launch ur_bringup ur5e.launch.py robot_ip:=192.168.56.101
```

I get a non-connected model in RViz until first measurements from the robot are received. Unfortunately, this spams my shell with 

```
[rviz2-4] Warning: Invalid frame ID "forearm_link" passed to canTransform argument source_frame - frame does not exist
[rviz2-4]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.12/src/buffer_core.cpp
```

This isn't a huge problem, but assuming that I am a new user and there is some misconfiguration, I will never see the error output from the driver, as it will be washed away by the RViz output. For example, when specifying a wrong IP address, the `[ERROR] [1639131784.497475349] [UR_Client_Library]: Connection setup failed for 192.168.56.10:29999` isn't that easy to find in between the RViz output (ok, it's red, but I have to scroll a while to find it. Again, assume I am a new user to ROS).

It might make sense to not send RViz output to the shell when it is being launched from the driver launchfile.

**Comment by VinDp** [comment]
This issue seems to be not persisting, currently the Rviz output is really contained and doesn't hide anymore relevant information.
