### ISSUE TITLE
Error: Unable to write to hardware...

### ISSUE THREAD

**Issue by mehtas73** [UniversalRobots/Universal_Robots_ROS2_Driver#264]
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [dashboard_client-2]: process started with pid [14348]
[INFO] [ros2_control_node-1]: process started with pid [14346]
[INFO] [robot_state_publisher-3]: process started with pid [14350]
[INFO] [rviz2-4]: process started with pid [14352]
[INFO] [spawner-5]: process started with pid [14354]
[INFO] [spawner-6]: process started with pid [14356]
[INFO] [spawner-7]: process started with pid [14358]
[INFO] [spawner-8]: process started with pid [14360]
[INFO] [spawner-9]: process started with pid [14362]
[ros2_control_node-1] 1639420075.880662 [0] ros2_contr: using network interface enp1s0 (udp/10.34.94.105) selected arbitrarily from: enp1s0, eno1
[dashboard_client-2] 1639420075.880662 [0] dashboard_: using network interface enp1s0 (udp/10.34.94.105) selected arbitrarily from: enp1s0, eno1
[dashboard_client-2] [INFO] [1639420075.903021759] [UR_Client_Library]: Connected: Universal Robots Dashboard Server
[dashboard_client-2] 
[robot_state_publisher-3] 1639420075.912579 [0] robot_stat: using network interface enp1s0 (udp/10.34.94.105) selected arbitrarily from: enp1s0, eno1
[robot_state_publisher-3] Link base had 0 children
[robot_state_publisher-3] Link base_link_inertia had 1 children
[robot_state_publisher-3] Link shoulder_link had 1 children
[robot_state_publisher-3] Link upper_arm_link had 1 children
[robot_state_publisher-3] Link forearm_link had 1 children
[robot_state_publisher-3] Link wrist_1_link had 1 children
[robot_state_publisher-3] Link wrist_2_link had 1 children
[robot_state_publisher-3] Link wrist_3_link had 1 children
[robot_state_publisher-3] Link flange had 1 children
[robot_state_publisher-3] Link tool0 had 0 children
[robot_state_publisher-3] [INFO] [1639420075.934047110] [robot_state_publisher]: got segment base
[robot_state_publisher-3] [INFO] [1639420075.934214957] [robot_state_publisher]: got segment base_link
[robot_state_publisher-3] [INFO] [1639420075.934232199] [robot_state_publisher]: got segment base_link_inertia
[robot_state_publisher-3] [INFO] [1639420075.934240683] [robot_state_publisher]: got segment flange
[robot_state_publisher-3] [INFO] [1639420075.934248917] [robot_state_publisher]: got segment forearm_link
[robot_state_publisher-3] [INFO] [1639420075.934256964] [robot_state_publisher]: got segment shoulder_link
[robot_state_publisher-3] [INFO] [1639420075.934264502] [robot_state_publisher]: got segment tool0
[robot_state_publisher-3] [INFO] [1639420075.934272822] [robot_state_publisher]: got segment upper_arm_link
[robot_state_publisher-3] [INFO] [1639420075.934281023] [robot_state_publisher]: got segment wrist_1_link
[robot_state_publisher-3] [INFO] [1639420075.934288951] [robot_state_publisher]: got segment wrist_2_link
[robot_state_publisher-3] [INFO] [1639420075.934296810] [robot_state_publisher]: got segment wrist_3_link
[ros2_control_node-1] [INFO] [1639420075.948631632] [URPositionHardwareInterface]: Starting ...please wait...
[ros2_control_node-1] [INFO] [1639420075.948721179] [URPositionHardwareInterface]: Initializing driver...
[ros2_control_node-1] [WARN] [1639420075.949934237] [UR_Client_Library]: No realtime capabilities found. Consider using a realtime system for better performance
[spawner-5] 1639420075.961602 [0]    python3: using network interface enp1s0 (udp/10.34.94.105) selected arbitrarily from: enp1s0, eno1
[spawner-6] 1639420075.961603 [0]    python3: using network interface enp1s0 (udp/10.34.94.105) selected arbitrarily from: enp1s0, eno1
[spawner-8] 1639420075.961604 [0]    python3: using network interface enp1s0 (udp/10.34.94.105) selected arbitrarily from: enp1s0, eno1
[spawner-9] 1639420075.963949 [0]    python3: using network interface enp1s0 (udp/10.34.94.105) selected arbitrarily from: enp1s0, eno1
[spawner-7] 1639420075.963949 [0]    python3: using network interface enp1s0 (udp/10.34.94.105) selected arbitrarily from: enp1s0, eno1
[rviz2-4] qt.qpa.xcb: could not connect to display 
[rviz2-4] qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
[rviz2-4] This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
[rviz2-4] 
[rviz2-4] Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
[rviz2-4] 
[ERROR] [rviz2-4]: process has died [pid 14352, exit code -6, cmd '/home/isea/ros2_galactic/ros2-linux/lib/rviz2/rviz2 -d /home/isea/workspace/ros_ur_driver/install/ur_description/share/ur_description/rviz/view_robot.rviz --ros-args -r __node:=rviz2'].
[ros2_control_node-1] [INFO] [1639420076.254038531] [UR_Client_Library]: Negotiated RTDE protocol version to 2.
[ros2_control_node-1] [INFO] [1639420076.254774644] [UR_Client_Library]: Setting up RTDE communication with frequency 500.000000
[ros2_control_node-1] [WARN] [1639420077.261871219] [UR_Client_Library]: DEPRECATION NOTICE: Passing the calibration_checksum to the UrDriver's constructor has been deprecated. Instead, use the checkCalibration(calibration_checksum) function separately. This notice is for application developers using this library. If you are only using an application using this library, you can ignore this message.
[ros2_control_node-1] [WARN] [1639420077.262566728] [UR_Client_Library]: No realtime capabilities found. Consider using a realtime system for better performance
[ros2_control_node-1] [ERROR] [1639420078.351915799] [UR_Client_Library]: The calibration parameters of the connected robot don't match the ones from the given kinematics config file. Please be aware that this can lead to critical inaccuracies of tcp positions. Use the ur_calibration tool to extract the correct calibration from the robot and pass that into the description. See [https://github.com/UniversalRobots/Universal_Robots_ROS_Driver#extract-calibration-information] for details.
[ros2_control_node-1] [WARN] [1639420078.352006924] [UR_Client_Library]: No realtime capabilities found. Consider using a realtime system for better performance
[ros2_control_node-1] [INFO] [1639420078.352415519] [URPositionHardwareInterface]: System successfully started!
[ros2_control_node-1] [INFO] [1639420078.357471193] [controller_manager]: update rate is 530 Hz
[ros2_control_node-1] [ERROR] [1639420078.359811119] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.361503049] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.363479041] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.365436681] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.367422329] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.369369333] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.371350909] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.373303720] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.375266391] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.377190932] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.379137385] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.381070494] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.383061781] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.385018890] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.386967632] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.388912427] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.390860509] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.392808113] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.394899689] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.396959779] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.398854397] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.400884573] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.402845572] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.404866284] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.406888768] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.408799405] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.410886226] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.412842393] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.414899691] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.416905965] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.418904239] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.420902622] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.422889117] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.424902418] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.426930875] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.428904473] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.430897815] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.432915715] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.434898370] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.436692081] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.438913515] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.440909144] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.442786902] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.444874927] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.446780502] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.448893198] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.450920532] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.452918912] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.454936681] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.456753804] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.458728771] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.460795834] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.462800095] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.464775595] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.466805249] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.468789278] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.470785091] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.472852582] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.474790070] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.476851293] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.478888451] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.480881649] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.482912881] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.484805332] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.486942603] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.488850501] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.490887612] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.492779145] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.494932142] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.497019903] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.498926247] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.500878014] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.502935335] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.504850561] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.506899753] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.508934707] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.510938136] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.512900737] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.514831281] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.516919829] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.518863269] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.520736506] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [INFO] [1639420078.520902513] [controller_manager]: Loading controller 'joint_trajectory_controller'
[ros2_control_node-1] [ERROR] [1639420078.522728325] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.524731678] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.526687433] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.528731662] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.530716405] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.532739637] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.534814210] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [INFO] [1639420078.535644184] [controller_manager]: Loading controller 'io_and_status_controller'
[ros2_control_node-1] [ERROR] [1639420078.540422960] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.540452307] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.542397067] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.544348435] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.546324008] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [INFO] [1639420078.546682561] [controller_manager]: Loading controller 'speed_scaling_state_broadcaster'
[ros2_control_node-1] [ERROR] [1639420078.548271797] [URPositionHardwareInterface]: Unable to write to hardware...
[spawner-9] [INFO] [1639420078.548737034] [spawner_joint_trajectory_controller]: Loaded joint_trajectory_controller
[ros2_control_node-1] [ERROR] [1639420078.550234183] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [INFO] [1639420078.550487077] [controller_manager]: Loading controller 'force_torque_sensor_broadcaster'
[ros2_control_node-1] [ERROR] [1639420078.552491693] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.554170058] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.556406880] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [INFO] [1639420078.556660914] [controller_manager]: Loading controller 'joint_state_broadcaster'
[ros2_control_node-1] [ERROR] [1639420078.559568674] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.560085413] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.562030071] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.563968763] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [INFO] [1639420078.564400304] [controller_manager]: Configuring controller 'joint_trajectory_controller'
[ros2_control_node-1] [INFO] [1639420078.564500627] [joint_trajectory_controller]: Command interfaces are [position] and and state interfaces are [position velocity].
[spawner-6] [INFO] [1639420078.564950801] [spawner_io_and_status_controller]: Loaded io_and_status_controller
[ros2_control_node-1] [ERROR] [1639420078.565919300] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [INFO] [1639420078.566395899] [joint_trajectory_controller]: Controller state will be published at 100.00 Hz.
[spawner-7] [INFO] [1639420078.567005874] [spawner_speed_scaling_state_broadcaster]: Loaded speed_scaling_state_broadcaster
[spawner-8] [INFO] [1639420078.567551220] [spawner_force_torque_sensor_broadcaster]: Loaded force_torque_sensor_broadcaster
[ros2_control_node-1] [ERROR] [1639420078.567861674] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [INFO] [1639420078.568849110] [joint_trajectory_controller]: Action status changes will be monitored at 20.00 Hz.
[ros2_control_node-1] [ERROR] [1639420078.569803919] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.571750726] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [INFO] [1639420078.571830674] [controller_manager]: Configuring controller 'io_and_status_controller'
[ros2_control_node-1] [INFO] [1639420078.572031266] [controller_manager]: Configuring controller 'speed_scaling_state_broadcaster'
[ros2_control_node-1] [INFO] [1639420078.572072264] [speed_scaling_state_broadcaster]: Publisher rate set to : 100.0 Hz
[ros2_control_node-1] [INFO] [1639420078.572760116] [controller_manager]: Configuring controller 'force_torque_sensor_broadcaster'
[ros2_control_node-1] [ERROR] [1639420078.573751272] [URPositionHardwareInterface]: Unable to write to hardware...
[spawner-5] [INFO] [1639420078.574569701] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
[ros2_control_node-1] [ERROR] [1639420078.575668565] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [INFO] [1639420078.576020220] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[ros2_control_node-1] [INFO] [1639420078.576056843] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[spawner-9] [INFO] [1639420078.576719498] [spawner_joint_trajectory_controller]: Configured and started joint_trajectory_controller
[ros2_control_node-1] [ERROR] [1639420078.577598388] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.579649502] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.581601576] [URPositionHardwareInterface]: Unable to write to hardware...
[spawner-5] [INFO] [1639420078.582138300] [spawner_joint_state_broadcaster]: Configured and started joint_state_broadcaster
[ros2_control_node-1] [ERROR] [1639420078.583540705] [URPositionHardwareInterface]: Unable to write to hardware...
[ros2_control_node-1] [ERROR] [1639420078.585468833] [URPositionHardwareInterface]: Unable to write to hardware...
[ERROR] [ros2_control_node-1]: process has died [pid 14346, exit code -11, cmd '/home/isea/workspace/ros_ur_driver/install/controller_manager/lib/controller_manager/ros2_control_node --ros-args --params-file /tmp/launch_params_h4sp6j00 --params-file /home/isea/workspace/ros_ur_driver/install/ur_bringup/share/ur_bringup/config/ur5e_update_rate.yaml --params-file /home/isea/workspace/ros_ur_driver/install/ur_bringup/share/ur_bringup/config/ur_controllers.yaml'].
[INFO] [spawner-9]: process has finished cleanly [pid 14362]
[INFO] [spawner-5]: process has finished cleanly [pid 14354]

**Comment by fmauch** [comment]
Could you please provide some more context? This might be a duplicated of #262

**Comment by mehtas73** [comment]
This is using the main branch. The behavior persists regardless whether the External URCAP is paused or playing

**Comment by fmauch** [comment]
I would assume that it is actually related, but if it doesn't get fixed by running external_control on the robot, there might be another problem involved.

**Comment by fmauch** [comment]
Closing this due to referring to a rather old version. If this issue still arises, please comment and / or reopen.
