### ISSUE TITLE
ursim_driver missing on the foxy branch

### ISSUE THREAD

**Issue by slabua** [UniversalRobots/Universal_Robots_ROS2_Driver#270]
Does it need to be back ported, perhaps?

**Comment by destogl** [comment]
Hi @slabua,

can you plaease check if #272 is working for you?

**Comment by slabua** [comment]
Hi @destogl,
Thank you, it's working for me.

One more question. Could you provide a use case for the ursim?
Currently, I have been using rviz as a front-end for moveit2, and I am able to see the mirrored movement into ursim by running the external control program.
Perhaps the usefulness of it is when it is used in the opposite direction? Namely, when controlling the robot from the sim itself, or?
Thank you.

**Comment by destogl** [comment]
On the second terminal is actually command-line access to the execution. You can mostly ignore it.

ursim is used to test the robot's controller without an access to a physical robot. It provides you with dynamics and commands as real robot would do.

**Comment by slabua** [comment]
@destogl thank you for the clarification~
