### ISSUE TITLE
Add Controller_stopper node to this driver

### ISSUE THREAD

**Issue by urmahp** [UniversalRobots/Universal_Robots_ROS2_Driver#289]
It would make sense to have a controller_stopper node in ROS2 similar to the one in [ROS1](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/tree/master/controller_stopper). 

I will start looking into rewriting the controller_stopper node from ROS1 into ROS2.

**Comment by destogl** [comment]
This is OK as a short-term solution. It will not be needed as of Humble.

**Comment by fmauch** [comment]
I think, this is not only a short-term solution, but also something useful for Foxy and Galactic users if things don't get backported.

**Comment by destogl** [comment]
Yes, they will not be back ported because of API and ABI stability.
