### ISSUE TITLE
ros2_control_test_nodes is a missing exec_depend but not available

### ISSUE THREAD

**Issue by fmauch** [UniversalRobots/Universal_Robots_ROS2_Driver#292]
Currently, we have launchfiles using `ros2_control_test_nodes` which are also referenced in our README.md.

I'd create a PR adding the dependency, but as it is not released for ROS galactic we should make our heads clear whether we want to keep it. Once we want to do a binary release we need to have all dependencies available in released form.

@destogl what are your assumptions on the chances of having this released?

If we don't see that `ros2_control_test_nodes` will be released, we might want to get rid of the launchfiles before we release the driver.

Currently, this affects
 * [ur_bringup/launch/test_forward_velocity_controller.launch.py](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_bringup/launch/test_forward_velocity_controller.launch.py)
 * [ur_bringup/launch/test_joint_trajectory_controller.launch.py](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_bringup/launch/test_joint_trajectory_controller.launch.py)
 * [ur_bringup/launch/test_scaled_joint_trajectory_controller.launch.py](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_bringup/launch/test_scaled_joint_trajectory_controller.launch.py)

**Comment by destogl** [comment]
@fmauch we are actually planning to release the test node, but they will be moved to another package in ros2_controllers repository.

We can track this on the following PRs:
- ros-controls/ros2_control_demos#150
- ros-controls/ros2_controllers#294

I will ping the WG to get this merged and released soon.
