### ISSUE TITLE
Galactic: the “Interact” tool does not work for “ur_manipulator” when following the moveit example

### ISSUE THREAD

**Issue by lmendyk** [UniversalRobots/Universal_Robots_ROS2_Driver#307]
The “Interact” tool  seems not working when trying to set the goal for the “ur_manipulator”.  The log which seems relevant to that is:

`[rviz2-3] [INFO] [1645710748.640870337] [moveit_ros_robot_interaction.robot_interaction]: No active joints or end effectors found for group 'ur_manipulator'. Make sure that kinematics.yaml is loaded in this node's namespace.
[rviz2-3] [INFO] [1645710748.646816651] [moveit_ros_visualization.motion_planning_frame]: group ur_manipulator
[rviz2-3] [INFO] [1645710748.646855345] [moveit_ros_visualization.motion_planning_frame]: Constructing new MoveGroup connection for group 'ur_manipulator' in namespace ''`

**Comment by lmendyk** [comment]
I'm using en_US.UTF-8 - since I had  problems with MoveIt tutorial [#1049](https://github.com/ros-planning/moveit2/issues/1049)
So this time it must be a different story.

**Comment by fmauch** [comment]
Thanks for pointing that out. There was  a regression in #278 which should be fixed by #308.
