### ISSUE TITLE
README still mentions the `ur_description` pkg in several places

### ISSUE THREAD

**Issue by AndyZe** [UniversalRobots/Universal_Robots_ROS2_Driver#355]
The README still mentions ur_description, but it has been moved out of this repo.

> Packages in the Repository:
> 
>     ur_bringup - launch file and run-time configurations, e.g. controllers.
>     ...
>     ur_description - description files for the UR robots: meshes, URDF/XACRO files, etc.

**Comment by fmauch** [comment]
Thanks for noticing!
