### ISSUE TITLE
PREEMPT_RT Recommendation/Utility?

### ISSUE THREAD

**Issue by danzimmerman** [UniversalRobots/Universal_Robots_ROS2_Driver#381]
The ROS1 driver had a [clear recommendation](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/doc/real_time.md) to use the `PREEMPT_RT` kernel patch with the e-Series robot.

I don't see that in the instructions here, and this is leading me down a rabbit hole on the state of real-time programming in ROS2, `ros2_control`, etc. Seems like scaled_joint_trajectory_controller and the [`ros2_controllers` joint trajectory controller](https://github.com/ros-controls/ros2_controllers/blob/master/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller.hpp) it inherits from are intended to work real time, and ROS2 in general is making more use of real-time features. However, since I haven't been working with a physical robot in ROS1 I don't have good grounding in the ROS1->ROS2 transition here or real-time features.

I'll keep digging on my own but:
 * Should I [work on setting up the `PREEMPT_RT` kernel](https://github.com/ros2/ros2_documentation/blob/rolling/source/Tutorials/Building-Realtime-rt_preempt-kernel-for-ROS-2.rst) if I'm going to work with the e-Series with this driver (specifically with the scaled joint trajectory controller?)
 * What's the best place to look for next steps if there are more steps than that? (DDS config, etc.)

**Comment by danzimmerman** [comment]
I guess ROS1 or ROS2 aside, the UR Client Library [recommends real-time scheduling](https://github.com/UniversalRobots/Universal_Robots_Client_Library#a-word-on-real-time-scheduling)

**Comment by livanov93** [comment]
@danzimmerman The recommendations on using `PREEMPT_RT` you find are also helpful for the ROS2 driver. You should add some **priority scheduling** code in the [ur_ros2_control_node](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_robot_driver/src/ur_ros2_control_node.cpp). Be free to take inspiration from [here](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/dab6cf75670f90170c30ca59b54bfa665ce426d5/ur_robot_driver/src/hardware_interface_node.cpp#L63-L113).

**Comment by danzimmerman** [comment]
Thanks, this answers my question... will close!
