### ISSUE TITLE
Calibration Guide Link Broken

### ISSUE THREAD

**Issue by martiangnome** [UniversalRobots/Universal_Robots_ROS2_Driver#384]
Hi there,

When I connect to my UR10e robots it says the calibration data isn’t correct. I followed it here and the link “calibration guide” is broken. It appears that this is supposed to be automated, but I’m having issues and would appreciate direction on how to troubleshoot this.

thanks!

**Comment by fmauch** [comment]
Which ROS distribution are you working with? And which link are you referring to?

This should get you started: https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_calibration/README.md

**Comment by fmauch** [comment]
This was closed by #451
