### ISSUE TITLE
URScript commands for gripper

### ISSUE THREAD

**Issue by Abelpy1** [UniversalRobots/Universal_Robots_ROS2_Driver#387]
Hi,

In `Universal_Robots_ROS_Driver`, we could send URScript commands to control the Onrobot rg2 gripper on the UR5e, using the topic `/ur_hardware_interface/script_command`. I am very confused that whether we could use URScript commands to control the gripper based on `Universal_Robots_ROS2_Driver (galactic)`?
    
Hope for the reply, thanks.

**Comment by fmauch** [comment]
Closing in favor of #251
