### ISSUE TITLE
Pass ur10e xacro into a workcell xacro directly without launch file? 

### ISSUE THREAD

**Issue by lcbw** [UniversalRobots/Universal_Robots_ROS2_Driver#388]
ros2 - foxy | ubutnu 20.04 |
I'm building a workcell that includes the geometry for a table, end effector, NIST assembly task board, and a ur10e. 

My workcell xacro needs to include the ur10e urdf. 
How do I import the ur10e urdf directly into an xacro with the new UR file structure? 

The instructions to retrieve the desired ur model from a launch file are extensive, but I do not see an analog for direct use in a workcell xacro. 

I have investigated the following. 
(1) In ROS 2, The xacro:include function does not support params capabilities. You have to include a xacro, and use it's name to reference it and give it parameters called "params" 

(2) In spite of that fact, the following does not work because the ur_macro.xacro does not recognize "ur_type" as a parameter. 

<xacro:ur_robot params="ur_type">
     <ur_type value="ur10e"/>
</xacro:ur_robot>
[UPDATE 06-10-22]
(3) I've also tried setting my xacro up as the following. 
```
...
  <xacro:include filename="$(find ur_description)/urdf/ur.urdf.xacro"/>

  <!-- Static environment -->
  <link name="world"/>

  <!-- ROBOTS -->
 <!-- UR -->
  <xacro:arg name="name" default="ur"/>
  <!-- parameters -->
  <xacro:arg name="prefix" default="ur_" />
  <xacro:arg name="joint_limit_params" default="$(find ur_description)/config/ur10e/joint_limits.yaml"/>
  <xacro:arg name="kinematics_params" default="$(find ur_description)/config/ur10e/default_kinematics.yaml"/>
  <xacro:arg name="physical_params" default="$(find ur_description)/config/ur10e/physical_parameters.yaml"/>
  <xacro:arg name="visual_params" default="$(find ur_description)/config/ur10e/visual_parameters.yaml"/>
  <xacro:arg name="safety_limits" default="false"/>
  <xacro:arg name="safety_pos_margin" default="0.15"/>
  <xacro:arg name="safety_k_position" default="20"/>
  <!-- ros2_control related parameters -->
  <xacro:arg name="use_fake_hardware" default="false" />
  <xacro:arg name="fake_sensor_commands" default="false" />

  <!-- arm -->
  <xacro:ur_robot
    prefix="$(arg prefix)"
    joint_limits_parameters_file="$(arg joint_limit_params)"
    kinematics_parameters_file="$(arg kinematics_params)"
    physical_parameters_file="$(arg physical_params)"
    visual_parameters_file="$(arg visual_params)"
    safety_limits="$(arg safety_limits)"
    safety_pos_margin="$(arg safety_pos_margin)"
    safety_k_position="$(arg safety_k_position)"
    use_fake_hardware="$(arg use_fake_hardware)"
    fake_sensor_commands="$(arg fake_sensor_commands)" />
    ...
    ```
My xacro still does not parse correctly, and it is hanging up at the include step for the ur_macro.xacro. I note the following instruction in the ur_macro.xacro file:
" NOTE this is NOT a URDF. It cannot directly be loaded by consumers
    expecting a flattened '.urdf' file. See the top-level '.xacro' for that
    (but note that .xacro must still be processed by the xacro command)."

And while this makes sense in the light of the error I'm receiving: 
  "' using yaml rules: yaml.safe_load() failed
expected '<document start>', but found '<scalar>'
  in "<unicode string>", line 11, column 28:
        expecting a flattened '.urdf' file. See the top-level ' ... "

I'm still using the xacro command to import an xacro, so I do not understand why it thinks it expects a "flattened urdf"

**Comment by fmauch** [comment]
From galactic on, we've changed the structure quite a bit. See https://github.com/UniversalRobots/Universal_Robots_ROS2_Description. With this structure, it should be possible to do what you would like to achieve.

This will most probably not be backported to Foxy, since there have been siginificant changes between foxy and galactic. Therefore, I am closing this issue.
