### ISSUE TITLE
All links on UR robot are colliding

### ISSUE THREAD

**Issue by TheFalcoGuy** [UniversalRobots/Universal_Robots_ROS2_Driver#413]
I am running the ROS2 Foxy branch of the driver and I am trying to get Moveit2 to work with my Ur5e robot. I ran the following commands in two separate terminals:

ros2 launch ur_bringup ur_control.launch.py ur_type:=ur5e robot_ip:=192.168.0.99 launch_rviz:=false

ros2 launch ur_bringup ur_moveit.launch.py ur_type:=ur5e robot_ip:=192.168.0.99 launch_rviz:=true

Moveit launches, however, my ur5 robot is completely red: 

![Screenshot from 2022-06-21 18-37-10](https://user-images.githubusercontent.com/90654537/174908358-5ccbcd0f-800e-470d-9ae4-166b241ae0cf.png)

This results in the robot not being able to plan a trajectory. Below is my log:
[INFO] [launch]: All log files can be found below /home/d-lab/.ros/log/2022-06-21-18-36-54-686575-dlab-Alienware-m15-R6-572767
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [move_group-1]: process started with pid [572773]
[INFO] [mongo_wrapper_ros.py-2]: process started with pid [572775]
[INFO] [rviz2-3]: process started with pid [572777]
[INFO] [static_transform_publisher-4]: process started with pid [572779]
[static_transform_publisher-4] [INFO] [1655851015.113225271] [static_transform_publisher]: Spinning until killed publishing transform from 'world' to 'base_link'
[move_group-1] [WARN] [1655851015.136367207] [move_group.move_group]: MoveGroup launched without ~default_planning_pipeline specifying the namespace for the default planning pipeline configuration
[move_group-1] [WARN] [1655851015.136414473] [move_group.move_group]: Falling back to using the the move_group node namespace (deprecated behavior).
[move_group-1] Parsing robot urdf xml string.
[move_group-1] [INFO] [1655851015.138694452] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.000740858 seconds
[move_group-1] [INFO] [1655851015.138721510] [moveit_robot_model.robot_model]: Loading robot model 'ur'...
[move_group-1] Link base had 0 children
[move_group-1] Link base_link_inertia had 1 children
[move_group-1] Link shoulder_link had 1 children
[move_group-1] Link upper_arm_link had 1 children
[move_group-1] Link forearm_link had 1 children
[move_group-1] Link wrist_1_link had 1 children
[move_group-1] Link wrist_2_link had 1 children
[move_group-1] Link wrist_3_link had 1 children
[move_group-1] Link flange had 1 children
[move_group-1] Link tool0 had 0 children
[move_group-1] [INFO] [1655851015.168787093] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-1] [INFO] [1655851015.168917699] [moveit.ros_planning_interface.moveit_cpp]: Listening to '/joint_states' for joint states
[move_group-1] [INFO] [1655851015.169275056] [moveit_ros.current_state_monitor]: Listening to joint states on topic '/joint_states'
[move_group-1] [INFO] [1655851015.169539949] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/move_group/planning_scene_monitor' for attached collision objects
[move_group-1] [INFO] [1655851015.169557304] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[move_group-1] [INFO] [1655851015.169714414] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/move_group/publish_planning_scene'
[move_group-1] [INFO] [1655851015.169723701] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[move_group-1] [INFO] [1655851015.169908074] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'collision_object'
[move_group-1] [INFO] [1655851015.170071002] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
[move_group-1] [WARN] [1655851015.170096181] [moveit.ros.occupancy_map_monitor]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
[move_group-1] [ERROR] [1655851015.170118180] [moveit.ros.occupancy_map_monitor]: No 3D sensor plugin(s) defined for octomap updates
[move_group-1] [INFO] [1655851015.172004435] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'move_group'
[move_group-1] [INFO] [1655851015.186417481] [moveit.ros_planning.planning_pipeline]: Using planning interface 'OMPL'
[move_group-1] [INFO] [1655851015.188517051] [moveit_ros.add_time_optimal_parameterization]: Param 'move_group.path_tolerance' was not set. Using default value: 0.100000
[move_group-1] [INFO] [1655851015.188533683] [moveit_ros.add_time_optimal_parameterization]: Param 'move_group.resample_dt' was not set. Using default value: 0.100000
[move_group-1] [INFO] [1655851015.188537069] [moveit_ros.add_time_optimal_parameterization]: Param 'move_group.min_angle_change' was not set. Using default value: 0.001000
[move_group-1] [INFO] [1655851015.188546594] [moveit_ros.fix_workspace_bounds]: Param 'move_group.default_workspace_bounds' was not set. Using default value: 10.000000
[move_group-1] [INFO] [1655851015.188555459] [moveit_ros.fix_start_state_bounds]: Param 'move_group.start_state_max_bounds_error' was set to 0.050000
[move_group-1] [INFO] [1655851015.188558584] [moveit_ros.fix_start_state_bounds]: Param 'move_group.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-1] [INFO] [1655851015.188564768] [moveit_ros.fix_start_state_collision]: Param 'move_group.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-1] [INFO] [1655851015.188569261] [moveit_ros.fix_start_state_collision]: Param 'move_group.jiggle_fraction' was not set. Using default value: 0.020000
[move_group-1] [INFO] [1655851015.188577340] [moveit_ros.fix_start_state_collision]: Param 'move_group.max_sampling_attempts' was not set. Using default value: 100
[move_group-1] [INFO] [1655851015.188585289] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Add Time Optimal Parameterization'
[move_group-1] [INFO] [1655851015.188592187] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
[move_group-1] [INFO] [1655851015.188594409] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
[move_group-1] [INFO] [1655851015.188596179] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
[move_group-1] [INFO] [1655851015.188612824] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
[move_group-1] [INFO] [1655851015.203198507] [moveit.plugins.moveit_simple_controller_manager]: Added FollowJointTrajectory controller for joint_trajectory_controller
[move_group-1] [INFO] [1655851015.203288190] [moveit.plugins.moveit_simple_controller_manager]: Returned 1 controllers in list
[move_group-1] [INFO] [1655851015.203631452] [moveit_ros.trajectory_execution_manager]: Trajectory execution is not managing controllers
[move_group-1] [INFO] [1655851015.203645109] [move_group.move_group]: MoveGroup debug mode is ON
[move_group-1] [INFO] [1655851015.211572300] [move_group.move_group]: 
[move_group-1] 
[move_group-1] ********************************************************
[move_group-1] * MoveGroup using: 
[move_group-1] *     - ApplyPlanningSceneService
[move_group-1] *     - ClearOctomapService
[move_group-1] *     - CartesianPathService
[move_group-1] *     - ExecuteTrajectoryAction
[move_group-1] *     - GetPlanningSceneService
[move_group-1] *     - KinematicsService
[move_group-1] *     - MoveAction
[move_group-1] *     - MotionPlanService
[move_group-1] *     - QueryPlannersService
[move_group-1] *     - StateValidationService
[move_group-1] ********************************************************
[move_group-1] 
[move_group-1] [INFO] [1655851015.211597981] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[move_group-1] [INFO] [1655851015.211604134] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context initialization complete
[move_group-1] Loading 'move_group/ApplyPlanningSceneService'...
[move_group-1] Loading 'move_group/ClearOctomapService'...
[move_group-1] Loading 'move_group/MoveGroupCartesianPathService'...
[move_group-1] Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
[move_group-1] Loading 'move_group/MoveGroupGetPlanningSceneService'...
[move_group-1] Loading 'move_group/MoveGroupKinematicsService'...
[move_group-1] Loading 'move_group/MoveGroupMoveAction'...
[move_group-1] Loading 'move_group/MoveGroupPlanService'...
[move_group-1] Loading 'move_group/MoveGroupQueryPlannersService'...
[move_group-1] Loading 'move_group/MoveGroupStateValidationService'...
[move_group-1] 
[move_group-1] You can start planning now!
[move_group-1] 
[mongo_wrapper_ros.py-2] [INFO] [1655851015.220188709] [mongodb]: Starting mongodb with db location /tmp/db listening on localhost:33829
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.250-0400 I CONTROL  [initandlisten] MongoDB starting : pid=572845 port=33829 dbpath=/tmp/db 64-bit host=dlab-Alienware-m15-R6
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.250-0400 I CONTROL  [initandlisten] db version v3.6.8
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.250-0400 I CONTROL  [initandlisten] git version: 8e540c0b6db93ce994cc548f000900bdc740f80a
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.250-0400 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.250-0400 I CONTROL  [initandlisten] allocator: tcmalloc
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.250-0400 I CONTROL  [initandlisten] modules: none
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.250-0400 I CONTROL  [initandlisten] build environment:
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.250-0400 I CONTROL  [initandlisten]     distarch: x86_64
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.250-0400 I CONTROL  [initandlisten]     target_arch: x86_64
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.250-0400 I CONTROL  [initandlisten] options: { net: { port: 33829 }, storage: { dbPath: "/tmp/db" } }
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.250-0400 I -        [initandlisten] Detected data files in /tmp/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.250-0400 I STORAGE  [initandlisten] 
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.250-0400 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.250-0400 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.250-0400 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=15410M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),cache_cursors=false,compatibility=(release="3.0",require_max="3.0"),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
[rviz2-3] [INFO] [1655851015.290446487] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] [INFO] [1655851015.290517320] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-3] [INFO] [1655851015.306207011] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-3] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occured with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[rviz2-3]          at line 253 in /opt/ros/foxy/include/class_loader/class_loader_core.hpp
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.490-0400 I STORAGE  [initandlisten] WiredTiger message [1655851015:490621][572845:0x7fe781e58ac0], txn-recover: Main recovery loop: starting at 16/5120
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.549-0400 I STORAGE  [initandlisten] WiredTiger message [1655851015:549196][572845:0x7fe781e58ac0], txn-recover: Recovering log 16 through 17
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.589-0400 I STORAGE  [initandlisten] WiredTiger message [1655851015:589234][572845:0x7fe781e58ac0], txn-recover: Recovering log 17 through 17
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.618-0400 I STORAGE  [initandlisten] WiredTiger message [1655851015:618798][572845:0x7fe781e58ac0], txn-recover: Set global recovery timestamp: 0
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.691-0400 I CONTROL  [initandlisten] 
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.691-0400 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.691-0400 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.691-0400 I CONTROL  [initandlisten] 
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.691-0400 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.691-0400 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.691-0400 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.691-0400 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.691-0400 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.691-0400 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.691-0400 I CONTROL  [initandlisten] 
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.717-0400 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/tmp/db/diagnostic.data'
[mongo_wrapper_ros.py-2] 2022-06-21T18:36:55.717-0400 I NETWORK  [initandlisten] waiting for connections on port 33829
[rviz2-3] [ERROR] [1655851018.387002268] [moveit_ros_visualization.motion_planning_frame]: Action server: /recognize_objects not available
[rviz2-3] Parsing robot urdf xml string.
[rviz2-3] [INFO] [1655851018.445607947] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.00105504 seconds
[rviz2-3] [INFO] [1655851018.445663311] [moveit_robot_model.robot_model]: Loading robot model 'ur'...
[rviz2-3] Link base had 0 children
[rviz2-3] Link base_link_inertia had 1 children
[rviz2-3] Link shoulder_link had 1 children
[rviz2-3] Link upper_arm_link had 1 children
[rviz2-3] Link forearm_link had 1 children
[rviz2-3] Link wrist_1_link had 1 children
[rviz2-3] Link wrist_2_link had 1 children
[rviz2-3] Link wrist_3_link had 1 children
[rviz2-3] Link flange had 1 children
[rviz2-3] Link tool0 had 0 children
[rviz2-3] [INFO] [1655851018.504962667] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[rviz2-3] [INFO] [1655851018.505485889] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/monitored_planning_scene'
[rviz2-3] [INFO] [1655851018.929903319] [interactive_marker_display_93861753369024]: Connected on namespace: rviz_moveit_motion_planning_display/robot_interaction_interactive_marker_topic
[rviz2-3] Link base had 0 children
[rviz2-3] Link base_link_inertia had 1 children
[rviz2-3] Link shoulder_link had 1 children
[rviz2-3] Link upper_arm_link had 1 children
[rviz2-3] Link forearm_link had 1 children
[rviz2-3] Link wrist_1_link had 1 children
[rviz2-3] Link wrist_2_link had 1 children
[rviz2-3] Link wrist_3_link had 1 children
[rviz2-3] Link flange had 1 children
[rviz2-3] Link tool0 had 0 children
[rviz2-3] [INFO] [1655851018.939828666] [moveit_ros_visualization.motion_planning_frame]: group ur_manipulator
[rviz2-3] [INFO] [1655851018.939840467] [moveit_ros_visualization.motion_planning_frame]: Constructing new MoveGroup connection for group 'ur_manipulator' in namespace ''
[rviz2-3] [WARN] [1655851018.939885460] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[rviz2-3] [INFO] [1655851018.944247735] [interactive_marker_display_93861753369024]: Sending request for interactive markers
[rviz2-3] [INFO] [1655851018.946494565] [move_group_interface]: Ready to take commands for planning group ur_manipulator.
[rviz2-3] [INFO] [1655851018.946531017] [move_group_interface]: Looking around: no
[rviz2-3] [INFO] [1655851018.946540267] [move_group_interface]: Replanning: no
[rviz2-3] [INFO] [1655851018.948236140] [moveit_ros_visualization.motion_planning_frame_planning]: POPULATING PLANNERS 12 grp: ur_manipulator
[rviz2-3] [INFO] [1655851018.948335067] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: ur_manipulator
[rviz2-3] [INFO] [1655851018.948339756] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: ur_manipulator[BKPIECEkConfigDefault]
[rviz2-3] [INFO] [1655851018.948392505] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: ur_manipulator[ESTkConfigDefault]
[rviz2-3] [INFO] [1655851018.948395916] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: ur_manipulator[KPIECEkConfigDefault]
[rviz2-3] [INFO] [1655851018.948398377] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: ur_manipulator[LBKPIECEkConfigDefault]
[rviz2-3] [INFO] [1655851018.948401083] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: ur_manipulator[PRMkConfigDefault]
[rviz2-3] [INFO] [1655851018.948403519] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: ur_manipulator[PRMstarkConfigDefault]
[rviz2-3] [INFO] [1655851018.948406737] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: ur_manipulator[RRTConnectkConfigDefault]
[rviz2-3] [INFO] [1655851018.948409265] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: ur_manipulator[RRTkConfigDefault]
[rviz2-3] [INFO] [1655851018.948411733] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: ur_manipulator[RRTstarkConfigDefault]
[rviz2-3] [INFO] [1655851018.948414403] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: ur_manipulator[SBLkConfigDefault]
[rviz2-3] [INFO] [1655851018.948417015] [moveit_ros_visualization.motion_planning_frame_planning]: planner id: ur_manipulator[TRRTkConfigDefault]
[rviz2-3] [INFO] [1655851018.977148153] [interactive_marker_display_93861753369024]: Service response received for initialization
[move_group-1] [INFO] [1655851212.542889952] [moveit_move_group_default_capabilities.move_action_capability]: Received request
[move_group-1] [INFO] [1655851212.543007695] [moveit_move_group_default_capabilities.move_action_capability]: executing..
[move_group-1] [INFO] [1655851212.544388932] [moveit_move_group_default_capabilities.move_action_capability]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[move_group-1] [INFO] [1655851212.544411186] [moveit_move_group_capabilities_base.move_group_capability]: Using planning pipeline 'move_group'
[move_group-1] [INFO] [1655851212.544670759] [moveit_collision_detection_fcl.collision_common]: Found a contact between 'shoulder_link' (type 'Robot link') and 'upper_arm_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
[move_group-1] [INFO] [1655851212.544682314] [moveit_collision_detection_fcl.collision_common]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[move_group-1] [INFO] [1655851212.544687278] [moveit_ros.fix_start_state_collision]: Start state appears to be in collision with respect to group ur_manipulator
[move_group-1] [WARN] [1655851212.557408251] [moveit_ros.fix_start_state_collision]: Unable to find a valid state nearby the start state (using jiggle fraction of 0.020000 and 100 sampling attempts). Passing the original planning request to the planner.
[move_group-1] [INFO] [1655851212.558056703] [moveit.ompl_planning.model_based_planning_context]: Planner configuration 'ur_manipulator' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[move_group-1] [WARN] [1655851212.558506782] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/base/src/Planner.cpp:257 - ur_manipulator/ur_manipulator: Skipping invalid start state (invalid state)
[move_group-1] [WARN] [1655851212.558519769] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/base/src/Planner.cpp:257 - ur_manipulator/ur_manipulator: Skipping invalid start state (invalid state)
[move_group-1] [ERROR] [1655851212.558533976] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:207 - ur_manipulator/ur_manipulator: Motion planning start tree could not be initialized!
[move_group-1] [WARN] [1655851212.558541085] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/base/src/Planner.cpp:257 - ur_manipulator/ur_manipulator: Skipping invalid start state (invalid state)
[move_group-1] [WARN] [1655851212.558570898] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/base/src/Planner.cpp:257 - ur_manipulator/ur_manipulator: Skipping invalid start state (invalid state)
[move_group-1] [ERROR] [1655851212.558587446] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:207 - ur_manipulator/ur_manipulator: Motion planning start tree could not be initialized!
[move_group-1] [ERROR] [1655851212.558621454] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:207 - ur_manipulator/ur_manipulator: Motion planning start tree could not be initialized!
[move_group-1] [ERROR] [1655851212.558630232] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:207 - ur_manipulator/ur_manipulator: Motion planning start tree could not be initialized!
[move_group-1] [WARN] [1655851212.558656861] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/tools/multiplan/src/ParallelPlan.cpp:138 - ParallelPlan::solve(): Unable to find solution by any of the threads in 0.000307 seconds
[move_group-1] [WARN] [1655851212.558748540] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/base/src/Planner.cpp:257 - ur_manipulator/ur_manipulator: Skipping invalid start state (invalid state)
[move_group-1] [ERROR] [1655851212.558765244] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:207 - ur_manipulator/ur_manipulator: Motion planning start tree could not be initialized!
[move_group-1] [WARN] [1655851212.558778798] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/base/src/Planner.cpp:257 - ur_manipulator/ur_manipulator: Skipping invalid start state (invalid state)
[move_group-1] [ERROR] [1655851212.558790802] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:207 - ur_manipulator/ur_manipulator: Motion planning start tree could not be initialized!
[move_group-1] [WARN] [1655851212.558795444] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/base/src/Planner.cpp:257 - ur_manipulator/ur_manipulator: Skipping invalid start state (invalid state)
[move_group-1] [WARN] [1655851212.558811634] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/base/src/Planner.cpp:257 - ur_manipulator/ur_manipulator: Skipping invalid start state (invalid state)
[move_group-1] [ERROR] [1655851212.558827750] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:207 - ur_manipulator/ur_manipulator: Motion planning start tree could not be initialized!
[move_group-1] [ERROR] [1655851212.558835471] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:207 - ur_manipulator/ur_manipulator: Motion planning start tree could not be initialized!
[move_group-1] [WARN] [1655851212.558855673] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/tools/multiplan/src/ParallelPlan.cpp:138 - ParallelPlan::solve(): Unable to find solution by any of the threads in 0.000142 seconds
[move_group-1] [WARN] [1655851212.558909116] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/base/src/Planner.cpp:257 - ur_manipulator/ur_manipulator: Skipping invalid start state (invalid state)
[move_group-1] [WARN] [1655851212.558916821] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/base/src/Planner.cpp:257 - ur_manipulator/ur_manipulator: Skipping invalid start state (invalid state)
[move_group-1] [ERROR] [1655851212.558924668] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:207 - ur_manipulator/ur_manipulator: Motion planning start tree could not be initialized!
[move_group-1] [ERROR] [1655851212.558930037] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp:207 - ur_manipulator/ur_manipulator: Motion planning start tree could not be initialized!
[move_group-1] [WARN] [1655851212.558940740] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/tools/multiplan/src/ParallelPlan.cpp:138 - ParallelPlan::solve(): Unable to find solution by any of the threads in 0.000057 seconds
[move_group-1] [WARN] [1655851212.568085225] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/base/goals/src/GoalLazySamples.cpp:129 - Goal sampling thread never did any work.
[move_group-1] [INFO] [1655851212.568176638] [moveit.ompl_planning.model_based_planning_context]: Unable to solve the planning problem
[move_group-1] [INFO] [1655851212.568210179] [moveit_move_group_default_capabilities.move_action_capability]: No motion plan found. No execution attempted.
[rviz2-3] [INFO] [1655851212.943228749] [move_group_interface]: Planning request accepted
[rviz2-3] [INFO] [1655851213.043452691] [move_group_interface]: Planning request aborted
[rviz2-3] [ERROR] [1655851213.143583669] [move_group_interface]: MoveGroupInterface::plan() failed or timeout reached

I am able to run Moveit on the panda arm from the Moveit tutorial. I am not sure what went wrong and would appreciate any help. Thanks

**Comment by fmauch** [comment]
I cannot reproduce this error. Could you try moving the robot to a different configuration? 

```
[move_group-1] [WARN] [1655851212.558916821] [ompl]: /tmp/binarydeb/ros-foxy-ompl-1.5.0/src/ompl/base/src/Planner.cpp:257 - ur_manipulator/ur_manipulator: Skipping invalid start state (invalid state)
```

indicates that there is a problem with that pose. Once we verified that this is a workaround, we can have a look why that is failing. What is the joint configuration of the pose shown in the screenshot above?

**Comment by TheFalcoGuy** [comment]
I tried moving the robot to several different configurations and the starting state is always invalid. I tried redoing an install of the ur driver and everything is still colliding with itself. I used the following commands to make an install

git clone -b foxy https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver.git src/Universal_Robots_ROS2_Driver
vcs import src --skip-existing --input src/Universal_Robots_ROS2_Driver/Universal_Robots_ROS2_Driver.repos
rosdep install --ignore-src --from-paths src -y -r
colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
source install/setup.bash


vcs import src --skip-existing --input src/Universal_Robots_ROS2_Driver/MoveIt_Support.repos
vcs import src --skip-existing --input src/moveit2/moveit2.repos
rosdep install --ignore-src --from-paths src -y -r
colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
source install/setup.bash


I did not record the joint configuration of the pose in the above screenshot. However, I have a joint configuration of a different pose that is in the same situation as the screenshot:
![Screenshot from 2022-06-22 10-57-29](https://user-images.githubusercontent.com/90654537/175062594-38c2579d-72ec-4baf-b14e-38edace84a58.png)

If it helps, I used the ur client library in my original install. However, in my new install, I did not use the ur client library.

**Comment by fmauch** [comment]
Could you maybe try a non-src build? All dependencies have been released and with the next foxy sync, the driver will also be installable using apt.

```
export COLCON_WS=~/workspace/ros_ur_driver
mkdir -p $COLCON_WS/src
cd $COLCON_WS
git clone -b foxy https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver.git src/Universal_Robots_ROS2_Driver
rosdep install --ignore-src --from-paths src -y -r
colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
source install/setup.bash
```

This should get you up and running.

**Comment by TheFalcoGuy** [comment]
I was able to get it working for a brief moment. My src directory had its own build and install directories, and removing that allowed moveit to work. Afterwards, I started working on making my own moveit configuration for a ur5 arm connected with a robotiq gripper, and added a package to the src directory. After building, the links started colliding with each other again. I have enclosed a google drive link to my code and you can build it. https://drive.google.com/drive/u/1/folders/1LKBRONLLT6IIjINZ09X5jhdLrBJM10BX .

**Comment by TheFalcoGuy** [comment]
I solved the problem - for some reason installing moveit from source causes the issue, but when you install the binary build (https://moveit.ros.org/install-moveit2/binary/) it works.
