### ISSUE TITLE
BUG with planning

### ISSUE THREAD

**Issue by yoavRobee** [UniversalRobots/Universal_Robots_ROS2_Driver#417]
i mannged to get it to plan in rviz with moveit
but when i try to execute the plan i get the following error :

[moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: Action client not connected to action server: scaled_joint_trajectory_controller/follow_joint_trajectory

**Comment by fmauch** [comment]
A bit more context how you started everything might be helpful. Real robot? URSim? Fake hardware?

Please provide the exact startup commands that you executed and the complete output of those.

**Comment by fmauch** [comment]
I'm glad to hear this has been resolved.

Could you please post your solution so others with a similar problem can get a hint how to solve this?
