### ISSUE TITLE
Humble - Not able to build UR driver correctly

### ISSUE THREAD

**Issue by vetletj** [UniversalRobots/Universal_Robots_ROS2_Driver#444]
Hello, 

I’m trying to build [Universal Robots ROS 2 Driver](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver) on Ubuntu 22.04 Humble, so I can control my UR10e with MoveIt2 on the latest distro. I’ve already done this with Ubuntu 20.04 Foxy, where everything works perfectly.

[Universal Robots ROS 2 Driver – Getting Started](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver#getting-started)
I’m running all commands as the guide instructs, on step 4. I’ve tried to import two different repos: 
```vcs import src --skip-existing --input src/Universal_Robots_ROS2_Driver/Universal_Robots_ROS2_Driver-not-released.humble.repos```
and
```vcs import src --skip-existing --input src/Universal_Robots_ROS2_Driver/Universal_Robots_ROS2_Driver.humble.repos```
Both give the same colcon warning and stdrr output when running colcon build :
```
tht@tht-stationary02:~/workspace/ros_ur_driver$ colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
[0.192s] WARNING:colcon.colcon_core.package_selection:Some selected packages are already built in one or more underlay workspaces:
	'gripper_controllers' is in: /opt/ros/humble
	'joint_state_broadcaster' is in: /opt/ros/humble
	'joint_trajectory_controller' is in: /opt/ros/humble
If a package in a merged underlay workspace is overridden and it installs headers, then all packages in the overlay must sort their include directories by workspace order. Failure to do so may result in build failures or undefined behavior at run time.
If the overridden package is used by another package in any underlay, then the overriding package in the overlay must be API and ABI compatible or undefined behavior at run time may occur.

If you understand the risks and want to override a package anyways, add the following to the command line:
	--allow-overriding gripper_controllers joint_state_broadcaster joint_trajectory_controller

This may be promoted to an error in a future release of colcon-override-check.
Starting >>> forward_command_controller
Starting >>> joint_trajectory_controller
Starting >>> force_torque_sensor_broadcaster
Starting >>> joint_state_broadcaster
Starting >>> ur_dashboard_msgs
Starting >>> ros2_controllers_test_nodes
Starting >>> diff_drive_controller
Starting >>> imu_sensor_broadcaster
Starting >>> ur_moveit_config
Starting >>> gripper_controllers
--- stderr: ros2_controllers_test_nodes
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< ros2_controllers_test_nodes [0.44s]
Finished <<< ur_moveit_config [0.50s] 
Finished <<< joint_state_broadcaster [1.03s]
Finished <<< ur_dashboard_msgs [1.04s]
Finished <<< gripper_controllers [1.17s]
Finished <<< joint_trajectory_controller [1.36s]
Starting >>> ur_controllers
Finished <<< force_torque_sensor_broadcaster [1.39s]
Finished <<< forward_command_controller [1.41s]
Starting >>> position_controllers
Starting >>> velocity_controllers
Starting >>> effort_controllers
Finished <<< diff_drive_controller [1.44s]
Finished <<< imu_sensor_broadcaster [1.68s]                                 
Finished <<< effort_controllers [1.22s]                              
Finished <<< position_controllers [1.23s]
Finished <<< velocity_controllers [1.23s]
Starting >>> ros2_controllers
Finished <<< ros2_controllers [0.17s]                                  
Finished <<< ur_controllers [1.45s]
Starting >>> ur_robot_driver
Starting >>> ur_bringup
Finished <<< ur_bringup [0.16s]                                       
Finished <<< ur_robot_driver [2.39s]                       
Starting >>> ur_calibration
Finished <<< ur_calibration [2.06s]                       
Starting >>> ur
Finished <<< ur [0.23s]                  

Summary: 19 packages finished [7.59s]
  1 package had stderr output: ros2_controllers_test_nodes
[tht@tht-stationary02](mailto:tht@tht-stationary02):~/workspace/ros_ur_driver$
```

[Example Commands for Testing the Driver](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver#example-commands-for-testing-the-driver)
When I’m trying to test the driver with fake hardware 
```ros2 launch ur_robot_driver ur_control.launch.py ur_type:=ur5e robot_ip:=yyy.yyy.yyy.yyy use_fake_hardware:=true launch_rviz:=true``` 
I’m getting this error output: 
```[ros2_control_node-1] [ERROR] [1658305698.325349307] [scaled_joint_trajectory_controller]: Speed scaling interface not found in hardware interface.```

Thanks for considering this, any input would be appreciated.

**Comment by michael-sbarra** [comment]
@vetletj Is there a reason you need to build the driver from source instead of using the pre-built apt packages? You can install the packages by running `sudo apt-get install ros2-humble-ur`, or adding a `<depend>ur</depend>` tag to a package manifest in your workspace and then run `rosdep install --from-paths src`. These install methods appear to be missing from the README.

**Comment by vetletj** [comment]
Hi @michael-sbarra, thanks for the input! No, no reason other than that's what was instructed in the installation guide. I deleted the old workspace (built from source) and then installed the packages by running ```sudo apt-get install ros-humble-ur ros-humble-ur-bringup```. Sadly I'm still getting the same error when trying to test the driver.

**Comment by fmauch** [comment]
Please see #448. This should be fixed with the current main branch and a binary release also has been triggered. I'm going to close this, as it should be fixed, but feel free to comment or reopen if the problem persists.
