### ISSUE TITLE
Goal_time_tolerance in ScaledJointTrajectoryController

### ISSUE THREAD

**Issue by MGBla** [UniversalRobots/Universal_Robots_ROS2_Driver#45]
We should discuss how to handle the goal_time_tolerance when the robot is scaled down.
Right now the scaling factor is not applied to the time tolerance, which will be a problem if a rather small tolerance is chosen and the robot scales its movement down. However from my point of view this is the desired behavior since the action fails if the user specified time tolerance is violated. But on the other hand the user might not be aware that the speed scaling will kick in which would lead to confusions why the action will return unsuccessful.

**Comment by fmauch** [comment]
I'd also say this is desired behavior. If a goal_time is requested and the robot cannot meet it, it should be an error return. Closing this.
