### ISSUE TITLE
Robot-specific update_rate.yaml configurations have no effect

### ISSUE THREAD

**Issue by dpiet** [UniversalRobots/Universal_Robots_ROS2_Driver#476]
Testing latest ROS2 Galactic package release, the `update_rate` parameter appears to be set purely by `ur_controllers.yaml` and the robot-specific yaml config for `update_rate` is ignored.

Reproduction:
Change `ur_bringup/config/ur_controllers.yaml` update_rate value.
```
$ ros2 launch ur_bringup ur_control.launch.py ur_type:=ur5e robot_ip:=<IP>
$ ros2 param get /controller_manager update_rate
```
Will show the new value and ignore the expected 500 Hz value in `ur5e_update_rate.yaml`.

**Comment by fmauch** [comment]
Will check that later this week thanks for reporting!
