### ISSUE TITLE
about robot_ip usage

### ISSUE THREAD

**Issue by tunahanertekin** [UniversalRobots/Universal_Robots_ROS2_Driver#491]
Hi there,

This is an issue just for a simple question. What is the functionality of `robot_ip` parameter? How should I populate this parameter? Can I give `127.0.0.1` for it, and what output should I expect if I can?

Thanks,
Tuna

**Comment by fmauch** [comment]
Well, when starting the driver, you'll want to connect to a robot using a network interface. As far as I recall, the argument is also required when launching in a simulated environment, in which case the values simply won't matter. This is certainly something that could be improved, though.
