### ISSUE TITLE
moveit2 ros2 universal robot grippers (rg2, rg6 etc.)

### ISSUE THREAD

**Issue by enriLoniterp** [UniversalRobots/Universal_Robots_ROS2_Driver#504]
I am interest in the model of the gripper of universal robot, it is available ?  there is some guide i could you use to implent it in my application? thank you very much

**Comment by fmauch** [comment]
Which gripper are you referring to? To my knowledge, not Universal Robot gripper exists.

**Comment by enriLoniterp** [comment]
https://www.universal-robots.com/plus/products/onrobot/rg2-gripper/

Rg2 gripper is sold to customers as universal robots gripper

**Comment by fmauch** [comment]
To my knowledge there doesn't exist a ROS2 driver for this, yet. Anyway, this would be out of scope for this driver, so I'll close this issue.

You'd need a ROS package for the gripper (description and driver), build a custom URDF containing the robot and the gripper, create a custom moveit config with that URDF and you would be good to go.
