### ISSUE TITLE
Updating ros_ur_driver fails

### ISSUE THREAD

**Issue by hagenfal** [UniversalRobots/Universal_Robots_ROS2_Driver#525]
Hello, 
I'm new at working with ROS especially the Universial_Robots_ROS2_Driver.
I have a program which was written on foxy. 
I've updated to humble and now I want to update the ros_ur_driver, so that the program may work again. 
Everything until rosdep update works but at rosdep install --ignore-src --from-paths src -y -r I'll get an error.

`ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
moveit_core: Cannot locate rosdep definition for [orocos_kdl]
moveit_kinematics: Cannot locate rosdep definition for [orocos_kdl]
warehouse_ros_mongo: No definition of [mongodb] for OS version [jammy]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully`

Moveit and orcos is installed and up to date.

Can anyone please help me with this issue?

Thanks in advance!

**Comment by fmauch** [comment]
Have you tried creating a new workspace following the README instructions? Quite a few things have changed since Foxy.

Also, unless you plan to contribute to the driver, we suggest installing the driver from binary packages (apt-get install ros-humble-ur) rather than building it from src.

**Comment by hagenfal** [comment]
Thanks for helping!
 
I've made a new workspace and now the driver works.
I still got the problem, that the driver doesn't work with my program, but that's probably a problem of my code.

**Comment by fmauch** [comment]
Thanks for reporting back. I'll go ahead and close this issue then.
