### ISSUE TITLE
Orientation problems while using URSIM with moveit

### ISSUE THREAD

**Issue by marioesteban11** [UniversalRobots/Universal_Robots_ROS2_Driver#554]
Hi everyone,

Im trying to do some programs while using ursim with moveit! and ur3e.

I have all the instalation well downloaded. And I run this following commands:

> ros2 run ur_robot_driver start_ursim.sh -m ur3e
To start the ursim vnc webpage

> ros2 launch ur_robot_driver ur_control.launch.py ur_type:=ur3e robot_ip:=192.168.56.101 launch_rviz:=false
To start ur3e controllers

And:
> ros2 launch ur_moveit_config ur_moveit.launch.py ur_type:=ur3e robot_ip:=192.168.56.1 use_fake_hardware:=false initial_joint_controller:=scaled_joint_trajectory_controller use_sim_time:=true
To start moveit:

After this, I also turn on the URCAPS extern controller in the vnc webpage, and with this after turning on program with urcaps in the ursim, i can move the robot using the ursim interface, and sending plans from RVIZ.

My problem comes when I try to move my robot with a c++ program. The position works perfectly, but the problem appears with the orientation that doesnt match where I want the robot to go. I will show you 2 photos, one of ursim orientation, and where i want the robot to go:

URSIM orientation:

![ursim_orientation](https://user-images.githubusercontent.com/48151661/205614080-dc3b5fa1-a006-471a-96a3-a6535597507b.png)

And program execution orientation:
![program_orientation](https://user-images.githubusercontent.com/48151661/205614231-58a4680b-5bd7-4018-888e-575f7cad232c.png)

I also try to set the orientation like this other form but it doesnt work neither:
![other_orientation](https://user-images.githubusercontent.com/48151661/205614628-9bdb575e-f59e-49d7-8b6e-f896180608a8.png)

This orientations are all in radians.

Thanks in advance. Hope you can help me.

**Comment by gavanderhoorn** [comment]
Isn't this the classical axis-angle <-> rpy 'problem'?

**Comment by marioesteban11** [comment]
Sry, I don´t know what that is @gavanderhoorn ... :((

**Comment by gavanderhoorn** [comment]
See [Explanation on robot orientation](https://www.universal-robots.com/articles/ur/application-installation/explanation-on-robot-orientation/) on the UR support site.

ROS defaults to using quaternions for orientations, which are often converted to RPY.

UR uses axis-angle by default. While you also see three numbers, you cannot (directly) compare them to each other.

It's been a while, but I believe you can configure the TP to display orientations in different formats. Either convert your script to display axis-angle values, or configure the TP to show you RPY.

**Comment by marioesteban11** [comment]
So, I cannot set a "normal" orientation. I mean I cannot say to the robot to move to a exact orientation?

I don´t really understand how this works

**Comment by fmauch** [comment]
I think I explained the problem in https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/570#issuecomment-1348195836.

**Comment by marioesteban11** [comment]
Yes, that issue solved my problem, thanks
