### ISSUE TITLE
Mistake in documentation: "For Humble use the galactic branch"

### ISSUE THREAD

**Issue by KarimHP** [UniversalRobots/Universal_Robots_ROS2_Driver#585]
In this (https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/tree/humble) link it says right under "Getting started"

```
Getting Started
[Install ROS2 Rolling](https://docs.ros.org/en/rolling/Installation/Ubuntu-Install-Debians.html). For using this driver with ROS2 foxy. Checkout [foxy branch](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/tree/foxy), for using it with ROS2 galactic, use the [galactic branch](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/tree/galactic), for using it with ROS2 humble, use the [galactic branch](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/tree/humble).
```

When i click on the link for humble it just redirects me to the humble repo but in the documentary it still says "install ros rolling". under Getting started. I think this can be a bit confusing, and am assuming its just a simple mistake made in the documentation. So im just hinting it should be fixed to avoid confusion :)

**Comment by fmauch** [comment]
Yes, that seems to have gotten mangled up, thanks for reporting this!
