### ISSUE TITLE
Update pre-commit and CI config

### ISSUE THREAD

**Issue by RobertWilbrandt** [UniversalRobots/Universal_Robots_ROS2_Driver#632]
We should try to be consistent with `Universal_Robots_ROS2_description` (see [58](https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/pull/58))

**Comment by destogl** [comment]
We are also constantly updating this on ros2_control – there you can also find the most updated version. Regarding GH actions  update, we added a bot to do that once per week.

**Comment by RobertWilbrandt** [comment]
Thanks for the hint. Dependabot seems like an easy thing to do, maybe we could also just add a scheduled workflow that does `pre-commit autoupdate` (something like [this](https://browniebroke.com/blog/gh-action-pre-commit-autoupdate/)).
