### ISSUE TITLE
Rolling testing repo builds failing due to MoveIt! dependency

### ISSUE THREAD

**Issue by fmauch** [UniversalRobots/Universal_Robots_ROS2_Driver#642]
MoveIt! seems to be having [problems in the buildfarm](https://build.ros2.org/job/Rbin_uJ64__moveit_core__ubuntu_jammy_amd64__binary/) currently, causing packages getting removed from the testing repo. This makes our pipelines building against the testing repo fail (binary and semi-binary).

We should first check, wether we can build against the latest MoveIt! release and then include this into the repos files until things have gone back to normal. Otherwise we are blind on issues coming from rolling testing at the moment.

---

Edit: MoveIt! has done a new release: https://github.com/ros/rosdistro/pull/36936. Maybe that fixes things.

**Comment by RobertWilbrandt** [comment]
This did indeed fix it
