### ISSUE TITLE
publish_state function parameter

### ISSUE THREAD

**Issue by JaisonJose241** [UniversalRobots/Universal_Robots_ROS2_Driver#644]
The ros2 doesn't seem to compile the moveit source build when running on ROS-Humble:

Line 262: ur_controllers/src/scaled_joint_trajectory_controller.cpp
  publish_state(time, state_desired, state_current, state_error);

But compiles perfectly when the same changes to: 
 publish_state(state_desired, state_current, state_error);

Is the error due to ros or the repo?

**Comment by RobertWilbrandt** [comment]
Are you sure you are building the driver from the `humble` branch? This API change was integrated in #612, which should not be relevant for humble.

**Comment by JaisonJose241** [comment]
My bad I had been building from main.

Resolved.
