### ISSUE TITLE
Controlling the robot arm through /scaled_joint_trajectory_controller/joint_trajectory topic

### ISSUE THREAD

**Issue by francescosemeraro** [UniversalRobots/Universal_Robots_ROS2_Driver#662]
Good afternoon!

In ROS 2 Humble, I would like to send joint configurations for the robot to assume through the /scaled_joint_trajectory_controller/joint_trajectory topic through a script in C++. I built a publisher that sends the exact positions of the test_scaled_joint_trajectory_controller.launch.py launch file. When I try to do that, the robot won't move. The message is received correctly by the topic, but for some reason the information is not processed. The launch file works okay. 
What am I missing? Is it possible that the launch file sets some options that cannot e seen in the script of publisher_joint-trajectory_controller.py?

`

#include "rclcpp/rclcpp.hpp"
#include "trajectory_msgs/msg/joint_trajectory.hpp"
#include "std_msgs/msg/float64_multi_array.hpp"
#include "trajectory_msgs/msg/joint_trajectory_point.hpp"
#include "builtin_interfaces/msg/duration.hpp"

int main(int argc, char * argv[])
{
    // Initialize the ROS 2 node
    rclcpp::init(argc, argv);
    auto node = std::make_shared<rclcpp::Node>("publisher_joint_trajectory");
    auto pub = node->create_publisher<trajectory_msgs::msg::JointTrajectory>(
        "/scaled_joint_trajectory_controller/joint_trajectory", 1);

    // Construct a JointTrajectory message containing the joint configuration
    auto msg = std::make_shared<trajectory_msgs::msg::JointTrajectory>();
    msg->joint_names = {"shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint",
                        "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"};
    auto point = std::make_shared<trajectory_msgs::msg::JointTrajectoryPoint>();
    point->positions = {double(0.785), double(-1.57), double(1.23), double(0.785), double(0.785), double(0.0)}; // Set the desired joint configuration here
    auto time_from_start = std::make_shared<builtin_interfaces::msg::Duration>();
    time_from_start->sec = int(4);
    point->time_from_start = *time_from_start; // Set the duration for this configuration
    msg->points.push_back(*point);

    // Publish the joint configuration
    pub->publish(*msg);

    // Spin the node until it is shutdown
    rclcpp::spin(node);

    // Shutdown the node
    rclcpp::shutdown();

    return 0;
}
`

**Comment by santoshbalaji** [comment]
There are few things you can check. 

1. First for JointTrajectoryPoint for all fields (velocities, accelerations, effort) give same size of data given for positions. Just array with value 0 for joint names will do.
2. Not sure whether you are trying work on real robot or simulation. In general you have to provide header timestamp which is part of joint trajectory message. This timestamp will be used for filtering messages of wrong timeline.
3. Worst case still have issues then you can try actions instead of using topics.

:)

**Comment by fmauch** [comment]
Just to add: Setting `time_from_start` might also be a good thing to do.

**Comment by fmauch** [comment]
I assume this can be closed. If there is still anything missing please comment and / or reopen.
