### ISSUE TITLE
Auto-update pre-commit hooks bot change committer

### ISSUE THREAD

**Issue by fmauch** [UniversalRobots/Universal_Robots_ROS2_Driver#678]
The current [implementation of that bot](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/fb5972dcd28425a73da3aa524493c9bc886f0f2c/.github/workflows/update-ci.yml) seems to use the wrong author information. It should be a bot and none of the actual committers.

**Comment by tungbq** [comment]
Hey @fmauch do you need help. I'd like to work on CI task like this. Can I pickup this task?

**Comment by fmauch** [comment]
Sure thing!
