### ISSUE TITLE
[Feature] - Add tf_prefix to logger name for hardware interface

### ISSUE THREAD

**Issue by firesurfer** [UniversalRobots/Universal_Robots_ROS2_Driver#691]
Currently the logger name for all hardware interface instances (and therefore instances of the UR client library) is the same. Therefore one can not distinguish reported errors.

Given that I am not 100% sure how the UrclLogHandler interacts with the client library I am adding this as a feature request instead of adding a PR.

**Comment by fmauch** [comment]
That's a very good idea. To achieve this, the `UrclLogHandler` would have to be made aware of the logging prefix and then all logging from the client library should be correctly prefixed.
