### ISSUE TITLE
Make PR to merge ur_msgs back to upstream

### ISSUE THREAD

**Issue by AndyZe** [UniversalRobots/Universal_Robots_ROS2_Driver#72]
Currently we use Denis' fork:

https://github.com/destogl/ur_msgs.git

We should get this merged back into https://github.com/ros-industrial/ur_msgs

**Comment by destogl** [comment]
https://github.com/ros-industrial/ur_msgs/pull/12

**Comment by fmauch** [comment]
ur_msgs is actually on the upstream repo and released as binary packages by now.
