### ISSUE TITLE
ur_moveit_config package and launch file not found in binary install

### ISSUE THREAD

**Issue by CharlesCDietzel** [UniversalRobots/Universal_Robots_ROS2_Driver#734]
I am attempting to use the ur_moveit.launch.py launch file with a UR5 robot. I am running the command in a Ubuntu 22.04 docker container connecting to the CB3 URSim docker image from here: https://hub.docker.com/r/universalrobots/ursim_cb3.

I am using ROS2 Humble, and I have installed the binary driver (version 2.2.8-1jammy.20230626.185638) in ubuntu as described in the README. However, when I try to run the launch file, this is the result:

`root@ur_controller:/workspace/src# ros2 launch ur_moveit_config ur_moveit.launch.py ur_type:=ur5 launch_rviz:=false robot_ip:=10.0.40.102`
`Package 'ur_moveit_config' not found: "package 'ur_moveit_config' not found, searching: ['/opt/ros/humble']"`

Other launch files (such as `ur_control.launch.py`) are found and work fine.

I then uninstalled the binary driver and installed from source, at which point `ur_moveit.launch.py` appeared and worked correctly. So it seems like somehow in the binary release the `ur_moveit_config` package is not being included. 

Any thoughts?

**Comment by fmauch** [comment]
Installing `ros-humble-ur-robot-driver` will not install the `ur_moveit_config` package. Maybe we should update the documentation accordingly, thanks for pointing that out!

To resolve, this, simply install `ros-humble-ur-moveit-config` (or `ros-humble-ur`).
