### ISSUE TITLE
Consider removing docker dependency from package.xml

### ISSUE THREAD

**Issue by firesurfer** [UniversalRobots/Universal_Robots_ROS2_Driver#769]
I suggest removing 

```
  <test_depend>docker.io</test_depend>
```

As this is a very large dependency where many people prob. want to explicitly decide whether they install it or not. If implicitly installed it can even be a security risk on some systems especially if users are unaware of it.

There is `--skip-keys=SKIP_KEYS` for `rosdep`. But in order to specify this option one has to be aware of what is installed which might not be the case especially for quickly put together testing environments.

**Comment by RobertWilbrandt** [comment]
I am not quite sure what to do with this.

We should have probably had this as an `exec_depend` previously, as the `start_ursim` script depended on it. Having it as a `test_depend` does not make sense when we don't call it directly from tests and all tests using ursim are optional through a flag. Seeing that we now have moved the script to the client library i see two options:
- Dropping it as dependency here, but adding it to the client library. This does not really change anything for the user, but would be more consistent.
- Drop the dependency altogether. The script would get logic to determine if docker is missing and warn about that.

I think i'd prefer the second option, as docker is not really needed for the majority of driver usage scenarios. @fmauch what do you think about this?

**Comment by fmauch** [comment]
Yes, dropping it from the driver makes sense and making the script generate good output if docker is missing seems like a fair solution. We'll have to remember installing docker in ci manually, then.

**Comment by fmauch** [comment]
I'll mark this an enhancement, as this is not necessarily at the top of our priority list.
