### ISSUE TITLE
Added freedrive mode functionality to ROS2

### ISSUE THREAD

**Issue by urrsk** [UniversalRobots/Universal_Robots_ROS2_Driver#772]

**Comment by fmauch** [comment]
I think I do have a feature branch for that lying around somewhere...

**Comment by ryanpennings** [comment]
Hi @fmauch, any update on this? And will it get merged into the humble branch?

**Comment by ZdenekM** [comment]
Having that would be great. I've seen some PRs in the ROS 1 driver repo...

**Comment by bodkal** [comment]
Is there an estimate of when the  #1114 will push to the main? tanks
