### ISSUE TITLE
ur_controllers build error due to class change in JTC

### ISSUE THREAD

**Issue by RobertWilbrandt** [UniversalRobots/Universal_Robots_ROS2_Driver#778]
https://github.com/ros-controls/ros2_controllers/pull/558 removed the `JointTrajectoryController::traj_point_active_ptr_` member, leading to CI and build farm build errors for iron and rolling.

**Comment by Yadunund** [comment]
@RobertWilbrandt i've opened a potential fix here https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/779.

Do you think you can review it asap to unblock the Iron sync? 😄
