### ISSUE TITLE
UR 20 driver support

### ISSUE THREAD

**Issue by adamdbrw** [UniversalRobots/Universal_Robots_ROS2_Driver#792]
With the recently added UR20 robot decription (https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/issues/35) I can see that the support for the new model is on the way. For us, it allows to easily import UR 20 into our simulation.

We are currently using these drivers to control some UR robots in our simulation. Is there a planned support for UR20 driver?

**Comment by fmauch** [comment]
Yes, I already have a feature branch on my other laptop, which I don't currently have with me. I'll push and PR this on Sunday.
