### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by timmarkhuff** [UniversalRobots/Universal_Robots_ROS2_Driver#824]
### Affected ROS2 Driver version(s)

-

### Used ROS distribution.

Humble

### Which combination of platform is the ROS driver running on.

Docker

### How is the UR ROS2 Driver installed.

From binary packets

### Which robot platform is the driver connected to.

UR CB3 robot

### Robot SW / URSim version(s)

-

### How is the ROS driver used.

Through the robot teach pendant using External Control URCap

### Issue details

On https://docs.ros.org/en/ros2_packages/rolling/api/ur_robot_driver/usage.html#using-moveit, there is a dead link, here: 

"Now you should be able to use the MoveIt Plugin in rviz2 to plan and execute trajectories with the robot as explained [here](https://moveit.picknik.ai/galactic/doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.html)."

### Accept Public visibility

- [X] I agree to make this context public

**Comment by fmauch** [comment]
Thank you for reporting this. I've created a fixing PR.
