### ISSUE TITLE
Unable to install ROS 2 UR Driver with Foxy branch

### ISSUE THREAD

**Issue by nqduy35** [UniversalRobots/Universal_Robots_ROS2_Driver#862]
Hello, I'm having trouble installing UR ROS 2 Driver following the guide in README of Foxy branch. Note that I have tried with Humble branch in another Ubuntu 22.04 laptop and everything works fine. 

In detail: 

- After running `$ rosdep update`, then `$ rosdep install --ignore-src --from-paths src -y` , I see the return: 
> ur_bringup: Cannot locate rosdep definition for [xacro]
> ur_robot_driver: Cannot locate rosdep definition for [ur_msgs]
> ur_controllers: Cannot locate rosdep definition for [ur_msgs]
> ur_dashboard_msgs: Cannot locate rosdep definition for [action_msgs]
> ur_description: Cannot locate rosdep definition for [xacro]
> ur_calibration: Cannot locate rosdep definition for [ur_client_library]
> ur_moveit_config: Cannot locate rosdep definition for [xacro]
> Continuing to install resolvable dependencies...
> #All required rosdeps installed successfully

- Then if I continue to run `$ colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release`, I have: 
> Starting >>> ur_dashboard_msgs
> Starting >>> ur_description
> Starting >>> ur_moveit_config
> --- stderr: ur_dashboard_msgs                                                                                                   
> CMake Error at CMakeLists.txt:4 (find_package):
>   By not providing "Findament_cmake.cmake" in CMAKE_MODULE_PATH this project
>   has asked CMake to find a package configuration file provided by
>   "ament_cmake", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "ament_cmake" with
>   any of the following names:
> 
>  ament_cmakeConfig.cmake
>  ament_cmake-config.cmake
> 
> Add the installation prefix of "ament_cmake" to CMAKE_PREFIX_PATH or set
> "ament_cmake_DIR" to a directory containing one of the above files.  If
> "ament_cmake" provides a separate development package or SDK, be sure it
> has been installed.
> 
> Failed   <<< ur_dashboard_msgs [0.32s, exited with code 1]
> Aborted  <<< ur_description [0.31s]
> Aborted  <<< ur_moveit_config [0.31s]
> 
> Summary: 0 packages finished [0.40s]
>   1 package failed: ur_dashboard_msgs
>   2 packages aborted: ur_description ur_moveit_config
>   3 packages had stderr output: ur_dashboard_msgs ur_description ur_moveit_config
>   4 packages not processed

Do you have any suggestion for me to control my UR with my laptop Ubuntu 20.04 ? Could you update the README in Foxy branch with a good instruction (if it is not correct)? Thank you.

**Comment by fmauch** [comment]
Hi, ROS 2 foxy is end-of-life and not supported anymore. This is also reflected in the `rosdep` command.  You might get further using `--include-eol-distros` to the `rosdep` commands, but I don't know whether this will completely resolve things. I expect things to at least build, since they still do in [our nightly CI jobs](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/actions/workflows/foxy-binary-build.yml?query=event%3Aschedule++).

However, since it is no longer supported I'll leave you with that and close this issue.
