### ISSUE TITLE
Add warning to the demo script in readme that it will move in zero configuration

### ISSUE THREAD

**Issue by MGBla** [UniversalRobots/Universal_Robots_ROS2_Driver#94]
We should add a warning for the demo script to specify how the robot will. This way the user is aware of what will happen and can remove cables etc. that might be damaged by the motion

**Comment by nbbrooks** [comment]
For each "Example Commands for Testing the Driver" demo
- Add instruction to move arm to home position before running
- Add instruction to check cable routing from base before running
- Add description of expected movement for each demo
- Add gif of demo's movement in rviz

**Comment by gavanderhoorn** [comment]
Why not check whether the joints are in a specific configuration (ie: elbow up, rest 0) before starting any motion?

And refuse if that's not the case.

That should not be difficult to check.

**Comment by MGBla** [comment]
This makes definitely sense as additional fail safe
