### ISSUE TITLE
pins missing label in io state msg

### ISSUE THREAD

**Issue by bblumberg** [UniversalRobots/Universal_Robots_ROS2_Driver#98]
In /io_and_status_controller/io_states, the pins are missing a correct label. My expectation would be that each pin has a unique label.
...
- pin: 0
  state: false
- pin: 0
  state: false
flag_states: []
analog_in_states:
- pin: 0
  domain: 1
  state: 4.192033767700195
- pin: 0
  domain: 1
  state: -0.0
analog_out_states:
- pin: 0
  domain: 1
  state: 0.0
- pin: 0
  domain: 1
  state: 0.0

**Comment by destogl** [comment]
@bblumberg: year you are right, we have an error there.

**Comment by MGBla** [comment]
Fixed in #103
