### ISSUE TITLE
Can i add Motion planning to work with collisions?

### ISSUE THREAD

**Issue by RalphGH7** [UniversalRobots/Universal_Robots_ROS2_Driver#989]
On the moveit site to test the panda robot i can add objects on the scene and control the robot from the motion planning in rviz but with this robot i can only control it from a different app (it automatically launch as settings) and the robot can collide with itself and i have NO PLANNING LIBRARY LOADED. 
What can i do to add the library and control the robot with collisions; and is there any tutorials on how to correctly do that. 
Thank You. 
![1](https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/assets/159960612/dadd613b-30bd-4bea-b5f3-4f0345e6d846)
![2](https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/assets/159960612/64a1d85f-737c-45d7-85b0-cf127e83ba58)
![3](https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/assets/159960612/6a0d6155-f091-4dd3-9765-de58e1ae5668)
![4](https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/assets/159960612/2d2392e8-f193-4caa-98bc-b418da301916)

**Comment by VinDp** [comment]
Hey @RalphGH7,
since a solution has been proposed and some time has passed I will close the issue. 
Feel free to re-open if relevant.
