### ISSUE TITLE
Add feature list markdown file

### ISSUE THREAD

**Issue by MGBla** [UniversalRobots/Universal_Robots_ROS2_Driver#99]
Using https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/master/ur_robot_driver/doc/features.md as a reference point

**Comment by fmauch** [comment]
Seems to be present https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_robot_driver/doc/features.md
